AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  MyLbUri:
    Type: String
    Default: "http://mytg-ded6222d8bc14f2c.elb.us-east-1.amazonaws.com"
  myHomePath:
    Type: String
    Default: "home1"
  myPostPath:
    Type: String
    Default: "post"
  apiGatewayRestPath:
    Type: String
    Default: "api"
  schedulesRestPath:
    Type: String
    Default: "bankId"

Resources:
  MyApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyApiCL1
      Description: Some Desc for my API Gateway
      EndpointConfiguration:
        Types:
          - REGIONAL

  MyApiResourceParams:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: MyApiGateway
      ParentId:
        Fn::GetAtt:
          - MyApiGateway
          - RootResourceId
      PathPart: !Ref apiGatewayRestPath

  MyApiResourceParamsSub:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MyApiGateway
      ParentId: !Ref MyApiResourceParams
      PathPart: "{id}"  

  MyApiMArkosMethod2:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref MyApiResourceParamsSub
      RestApiId: !Ref MyApiGateway        
      Integration:
        IntegrationHttpMethod: GET
        Type: HTTP_PROXY
        Uri: !Sub "http://nlb-940e8719651afb94.elb.us-east-1.amazonaws.com:8080/api/outbound/v1/schedules/bankId/{bankId}"
        PassthroughBehavior: WHEN_NO_MATCH
        RequestParameters: 
        #   integration.request.querystring.name: "method.request.querystring.name"
        #   integration.request.querystring.age: "method.request.querystring.age"
          integration.request.path.bankId: "method.request.path.id"
      RequestParameters:
        method.request.querystring.name: true
        method.request.querystring.age: false
        method.request.path.id: true
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
            method.response.header.Content-Type: true

  MyApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - MyApiMArkosMethod2
    Properties:
      RestApiId: !Ref MyApiGateway

  MyApiGatewayStage:
     Type: AWS::ApiGateway::Stage
     Properties:
       DeploymentId: !Ref MyApiDeployment
       RestApiId: !Ref MyApiGateway
      #  StageName: "v1"
       Description: "My API Gateway Stage Description"
       MethodSettings:
         - HttpMethod: "*"
           ResourcePath: "/*"
           ThrottlingBurstLimit: 500
           ThrottlingRateLimit: 1000
