AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
        - Key: Name
          Value: myVpcCF

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: "10.0.1.0/24"
      Tags:
        - Key: Name
          Value: mySubnetCF

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: mySecGpCF
      GroupDescription: Security group for NLB
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0   # Allow all inbound traffic (adjust as needed)
      VpcId: !Ref MyVPC
